name: daily beerzie
favicon: null
layout_spectrum: 0.8535762357059866
typography_spectrum: 0.161771054379642
title: daily beerzie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.04965544864535332
  lightness: 0.3379289647564292
  saturation: 0.8468887391500175
  rhythmicContrast: 0.09685832378454506
purpose: []
