color:
  brandStrength: 0
  saturation: 0.8468887
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.2510638
  rhythmicContrast: 0.6574468
title: daily rick
analytics:
  twitter: null
  google: null
  facebook: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0
purpose: []
name: daily rick
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 1
